steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "functions",
        "deploy",
        "meetup-stats",
        "--region=asia-northeast1",
        "--source https://source.developers.google.com/projects/expanded-league-162223/repos/meetup-stats/moveable-aliases/master/paths//",
        "--trigger-http",
      ]
